/** Shared Tailwind classes for tenant admin (dark glass theme). */
export const ui = {
  page: 'space-y-6',
  pageWide: 'space-y-8',
  title: 'text-2xl font-bold text-white',
  subtitle: 'mt-1 text-sm text-white/50',
  sectionTitle: 'text-lg font-semibold text-white/90',
  label: 'mb-1 block text-sm font-medium text-white/75',
  muted: 'text-sm text-white/45',
  card: 'glass-card rounded-2xl p-5 sm:p-6',
  cardStrong: 'glass-card-strong rounded-2xl p-5 sm:p-6',
  input: 'glass-input w-full rounded-xl px-3 py-2.5 text-sm',
  btnPrimary: 'btn-accent rounded-xl px-4 py-2.5 text-sm font-semibold disabled:cursor-not-allowed disabled:opacity-50',
  btnSecondary: 'btn-glass rounded-xl px-4 py-2.5 text-sm font-medium',
  btnGhost: 'rounded-xl border border-white/10 px-3 py-1.5 text-sm text-white/70 hover:bg-white/5',
  btnDanger: 'rounded-xl border border-red-400/30 bg-red-500/10 px-3 py-1.5 text-sm text-red-300 hover:bg-red-500/20',
  alertError: 'rounded-xl border border-red-400/30 bg-red-500/10 px-4 py-3 text-sm text-red-300',
  alertSuccess: 'rounded-xl border border-emerald-400/30 bg-emerald-500/10 px-4 py-3 text-sm text-emerald-300',
  alertInfo: 'rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-white/70',
  empty: 'glass-card rounded-2xl p-8 text-center',
  spinner: 'h-8 w-8 animate-spin rounded-full border-4 border-white/20 border-t-amber-400',
  divider: 'border-white/10',
  listItem: 'glass-card rounded-2xl p-4',
  modalOverlay: 'fixed inset-0 z-50 flex items-end justify-center bg-black/60 p-4 backdrop-blur-sm sm:items-center',
  modal: 'glass-card-strong w-full max-w-md rounded-2xl p-5 shadow-2xl',
} as const;
